service: rule-validation-api
app: rule-validation-api

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  profile: default #use ur IAM profile name here
  description : this function is the lambda function for rule-validation-api
  stage: dev
  region: eu-west-2
  memorySize: 512
  timeout: 120 #2 minutes time out
  stackName: rule-validation-api
  apiName: rule-validation-api
  deploymentBucket:
    name : serverless-user #create a bucket and add the name here
  deploymentPrefix: testing
functions:
  create-payment-tenant-app:
    handler: lambda.handler
    name: rule-validation-api
    # optimize:
    #   minify : false
    events : 
      - http:
          path: /{proxy+}
          method: any
          cors: true
          private: false